### ISSUE TITLE
API Adding records unkown database column.

### ISSUE THREAD

**Issue by isdinAghmir** [pan-net/terraform-provider-powerdns#89]
Hi there,

When trying to add a records via Terraform, it will try to add data to an unknown column.

column name : changed_when, in table records.

added it manually as a workaround in my powerdns database in the records table.

Official PowerDns schema do not have this column, so I think removing it from your API is not a bad idea.

br.

**Comment by mbag** [comment]
hi,

this is just terraform provider which communicates with PowerDNS API. If there is problem with PowerDNS API not validating input and trying to add data to the non- existing column, this should be reported directly to PowerDNS team: https://github.com/PowerDNS/pdns

Which version of the PowerDNS and which version of the provider were you using when you got this error? Can you provide terraform traceback and some minimal terraform configuration that causes this error?

**Comment by mbag** [comment]
@isdinAghmir

**Comment by isdinAghmir** [comment]
Hi ! 
@mbag you were right, powerdns was installed via ansible and somehow it installed the wrong version -- very outdated. < 4.1

Thanks for your support. 

This issue is then un-related to the terraform provider as you said.

thank you.

Best regards

**Comment by mbag** [comment]
@isdinAghmir  thank you for the update and for closing issue :+1:
