### ISSUE TITLE
Build provider for Darwin ARM64 (Mac M1)

### ISSUE THREAD

**Issue by RomLecat** [pan-net/terraform-provider-powerdns#90]
Hi,

Now that recent Mac uses a new CPU architecture (Apple Silicon) based on ARM64 and with compatible Terraform builds, could you please build this provider for darwin arm64 ?

Thanks!

**Comment by Hakujou** [comment]
If anyone is interested, I built the provider for ARM64: [terraform-provider-powerdns_darwin_arm64_v1.4.1.zip](https://github.com/pan-net/terraform-provider-powerdns/files/6826246/terraform-provider-powerdns_darwin_arm64_v1.4.1.zip)

Extract and move the file to `~/.terraform.d/plugins/registry.terraform.io/pan-net/powerdns/1.4.1/darwin_arm64`.

**Comment by splashx** [comment]
The build has been added on 1.4.1 release.

I order to avoid breaking changes, the following changes were made:

- New darwin_arm64 was added (all other arch releases were left untouched)
- A new SHA256SUM file and signature were created (one line added for the new file) and replaced in the release list

@mbag maybe a new section in the README worth adding "Release" req? `golang > 1.16` etc.

**Comment by mbag** [comment]
@splashx  I've added to README Requirements section the Go version >=1.16 and Goreleaser version >= v0.157.0 based on https://goreleaser.com/deprecations/#builds-for-darwinarm64

**Comment by RomLecat** [comment]
Thanks!
Would you mind publishing it to Terraform Registry too ? We still have to install it manually because TF Registry is still at 1.4.0.

**Comment by splashx** [comment]
@RomLecat thanks for pointing that out, we were not aware the webhook missed the `v1.4.1` tag/release. Could you please check now if everything is in order?

**Comment by RomLecat** [comment]
Release is now present and working on TF registry, thanks a lot!
