### ISSUE TITLE
Request Release

### ISSUE THREAD

**Issue by jbe-dw** [pan-net/terraform-provider-powerdns#92]
Hi there,

Thank you for merging my last patch. Do you plan to do a release any time soon ?

Regards

**Comment by jbe-dw** [comment]
@mbag Please, could you find some time to do it ? I appreciate that you finally got time to merge my PR, but we need a new release to use it with our terraform code.

Regards

**Comment by jbe-dw** [comment]
Update

**Comment by mbag** [comment]
published, sorry for long delay. I see the release here on github: https://github.com/pan-net/terraform-provider-powerdns/releases  however, I still don't see it on Terraform Registry: https://registry.terraform.io/providers/pan-net/powerdns/latest

**Comment by jbe-dw** [comment]
https://www.terraform.io/registry/providers/publishing#publishing-to-the-registry

If no github workflow is set in the project I think you have to manually publish the release in the registry.

**Comment by mbag** [comment]
I just realized I signed the release with the wrong GPG key. I had to re-release the provider and do manual resync of the provider on Registry. It might take few minutes, to pull changes from Github.

**Comment by mbag** [comment]
the v1.5.0 is ready https://registry.terraform.io/providers/pan-net/powerdns/1.5.0

**Comment by jbe-dw** [comment]
Thank you !
